"""empty message

Revision ID: 3a8bbe452cc1
Revises: 9087852000d2
Create Date: 2023-07-27 02:36:07.059230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a8bbe452cc1'
down_revision = '9087852000d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_text', sa.Text(), nullable=True))
        batch_op.drop_column('comment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.TEXT(), nullable=True))
        batch_op.drop_column('review_text')

    # ### end Alembic commands ###
