"""empty message

Revision ID: aad947b4f695
Revises: 2796c5289a82
Create Date: 2023-07-19 16:13:24.976944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aad947b4f695'
down_revision = '2796c5289a82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_comics',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comic_id'], ['comics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'comic_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('collection')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collection', sa.VARCHAR(length=255), nullable=True))

    op.drop_table('user_comics')
    # ### end Alembic commands ###
